"""Post-generation steps: secrets, git, dependency install.

Ordering here is security-critical. ``.env`` is written with 0600 permissions and
``.gitignore`` is verified to cover it *before* ``git init`` stages anything, so a
freshly generated project can never have secrets in its first commit.
"""

from __future__ import annotations

import os
import secrets
import shutil
import stat
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from basivo_auth.config import Database, EmailProvider, Feature, ProjectAnswers

ENV_FILE = ".env"
ENV_EXAMPLE = ".env.example"
GITIGNORE = ".gitignore"

# Secrets are 64 URL-safe bytes (~512 bits of entropy). Overkill is free here.
SECRET_BYTES = 64


@dataclass(slots=True)
class PostGenReport:
    secrets_written: bool = False
    git_initialised: bool = False
    initial_commit: str | None = None
    dependencies_installed: bool = False
    formatted: bool = False
    warnings: list[str] = field(default_factory=list)


def _new_secret() -> str:
    return secrets.token_urlsafe(SECRET_BYTES)


def build_env(answers: ProjectAnswers) -> dict[str, str]:
    """Compose the generated project's ``.env``.

    Every value that must be secret is generated here, never templated, so no
    secret ever exists inside the template repository.
    """
    env: dict[str, str] = {
        "ENVIRONMENT": "development",
        "DEBUG": "true",
        "SECRET_KEY": _new_secret(),
        "JWT_SECRET": _new_secret(),
        "REFRESH_TOKEN_SECRET": _new_secret(),
        "CSRF_SECRET": _new_secret(),
        "ACCESS_TOKEN_TTL_SECONDS": str(answers.access_token_ttl_seconds),
        "REFRESH_TOKEN_TTL_SECONDS": str(answers.refresh_token_ttl_seconds),
        "PUBLIC_BASE_URL": "http://localhost:8000",
        "FRONTEND_BASE_URL": "http://localhost:3000",
        "CORS_ORIGINS": "http://localhost:3000",
    }

    if answers.uses_redis:
        env["REDIS_URL"] = "redis://localhost:6379/0"

    if answers.database is Database.POSTGRES:
        db_password = secrets.token_urlsafe(24)
        env["POSTGRES_USER"] = answers.package_name
        env["POSTGRES_PASSWORD"] = db_password
        env["POSTGRES_DB"] = answers.package_name
        env["DATABASE_URL"] = (
            f"{answers.database.driver}://{answers.package_name}:{db_password}"
            f"@localhost:5432/{answers.package_name}"
        )
    else:
        env["DATABASE_URL"] = f"{answers.database.driver}:///./{answers.package_name}.db"

    if answers.email_provider is EmailProvider.SMTP:
        env |= {
            "SMTP_HOST": "localhost",
            "SMTP_PORT": "1025",
            "SMTP_USER": "",
            "SMTP_PASSWORD": "",
            "SMTP_TLS": "false",
        }
    elif answers.email_provider is EmailProvider.RESEND:
        env["RESEND_API_KEY"] = ""
    elif answers.email_provider is EmailProvider.SES:
        env |= {"AWS_REGION": "us-east-1", "AWS_ACCESS_KEY_ID": "", "AWS_SECRET_ACCESS_KEY": ""}

    env["EMAIL_FROM"] = f"no-reply@{answers.project_slug}.local"
    env["EMAIL_FROM_NAME"] = answers.project_name

    if answers.has(Feature.SSO):
        env |= {
            "GOOGLE_CLIENT_ID": "",
            "GOOGLE_CLIENT_SECRET": "",
            "GITHUB_CLIENT_ID": "",
            "GITHUB_CLIENT_SECRET": "",
            "OIDC_DISCOVERY_URL": "",
            "OIDC_CLIENT_ID": "",
            "OIDC_CLIENT_SECRET": "",
        }
    if answers.has(Feature.TOTP):
        env["TOTP_ISSUER"] = answers.project_name
    if answers.has(Feature.PASSKEYS):
        env |= {
            "WEBAUTHN_RP_ID": "localhost",
            "WEBAUTHN_RP_NAME": answers.project_name,
            "WEBAUTHN_ORIGIN": "http://localhost:3000",
        }
    if answers.has(Feature.SAML):
        env |= {"SAML_SP_ENTITY_ID": "", "SAML_IDP_METADATA_URL": ""}

    return env


def _render_env(env: dict[str, str]) -> str:
    lines = [
        "# Generated by basivo-auth. NEVER commit this file.",
        "# Secrets below were generated locally with `secrets.token_urlsafe`.",
        "",
    ]
    lines.extend(f"{key}={value}" for key, value in env.items())
    return "\n".join(lines) + "\n"


def ensure_gitignored(project: Path, report: PostGenReport) -> None:
    """Guarantee .env is ignored. Runs before git init, and is not optional."""
    gitignore = project / GITIGNORE
    existing = gitignore.read_text(encoding="utf-8") if gitignore.is_file() else ""
    patterns = {line.strip() for line in existing.splitlines()}

    required = [".env", ".env.*", "!.env.example"]
    missing = [pattern for pattern in required if pattern not in patterns]
    if not missing:
        return

    block = "\n# --- basivo-auth: never commit local secrets ---\n" + "\n".join(missing) + "\n"
    with gitignore.open("a", encoding="utf-8") as handle:
        if existing and not existing.endswith("\n"):
            handle.write("\n")
        handle.write(block)


def write_env_files(project: Path, answers: ProjectAnswers, report: PostGenReport) -> None:
    env = build_env(answers)

    env_path = project / ENV_FILE
    if env_path.exists():
        report.warnings.append(f"{ENV_FILE} already exists; left untouched.")
        return

    env_path.write_text(_render_env(env), encoding="utf-8")
    # Owner read/write only. Secrets must not be world-readable on shared machines.
    env_path.chmod(stat.S_IRUSR | stat.S_IWUSR)

    # The example file mirrors the keys with the values stripped, so it is safe
    # to commit and doubles as the deployment checklist.
    placeholder_safe = {
        "ENVIRONMENT",
        "DEBUG",
        "PUBLIC_BASE_URL",
        "FRONTEND_BASE_URL",
        "CORS_ORIGINS",
        "REDIS_URL",
        "SMTP_HOST",
        "SMTP_PORT",
        "SMTP_TLS",
        "EMAIL_FROM",
        "EMAIL_FROM_NAME",
        "TOTP_ISSUER",
        "WEBAUTHN_RP_ID",
        "WEBAUTHN_RP_NAME",
        "WEBAUTHN_ORIGIN",
        "AWS_REGION",
        "ACCESS_TOKEN_TTL_SECONDS",
        "REFRESH_TOKEN_TTL_SECONDS",
    }
    example = {key: (value if key in placeholder_safe else "") for key, value in env.items()}
    example_path = project / ENV_EXAMPLE
    example_path.write_text(
        "# Copy to .env and fill in. `basivo-auth secrets rotate` regenerates the secrets.\n\n"
        + "\n".join(f"{key}={value}" for key, value in example.items())
        + "\n",
        encoding="utf-8",
    )

    report.secrets_written = True


def _git(project: Path, *args: str) -> subprocess.CompletedProcess[str]:
    git = shutil.which("git")
    if git is None:
        raise FileNotFoundError("git not found on PATH")
    return subprocess.run(
        [git, "-C", str(project), *args],
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )


def init_git(project: Path, report: PostGenReport) -> None:
    """Initialise a git repo and make the first commit.

    ``copier update`` requires the destination to be a clean git repo, so this is
    a functional requirement of the update channel, not a convenience.
    """
    if (project / ".git").exists():
        report.warnings.append("Existing git repository detected; skipped git init.")
        return

    if shutil.which("git") is None:
        report.warnings.append("git not found; skipped repo init. `copier update` will not work.")
        return

    init = _git(project, "init", "-b", "main")
    if init.returncode != 0:
        report.warnings.append(f"git init failed: {init.stderr.strip()}")
        return
    report.git_initialised = True

    _git(project, "add", "-A")

    status = _git(project, "status", "--porcelain")
    if ".env\n" in status.stdout or status.stdout.strip().endswith(".env"):
        # Belt and braces: refuse to commit if .env somehow got staged.
        _git(project, "reset")
        report.warnings.append("Refused initial commit: .env was staged. Check .gitignore.")
        return

    commit = _git(
        project,
        "-c",
        "user.name=basivo-auth",
        "-c",
        "user.email=noreply@basivo.local",
        "commit",
        "-m",
        "chore: scaffold auth service with basivo-auth",
        "--no-verify",
    )
    if commit.returncode == 0:
        rev = _git(project, "rev-parse", "--short", "HEAD")
        report.initial_commit = rev.stdout.strip() or None
    else:
        report.warnings.append(f"Initial commit failed: {commit.stderr.strip()}")


def install_dependencies(project: Path, answers: ProjectAnswers, report: PostGenReport) -> None:
    uv = shutil.which("uv")
    if uv is None:
        report.warnings.append("uv not found; skipped dependency install. Run `uv sync` manually.")
        return

    proc = subprocess.run(
        [uv, "sync", "--python", answers.python_version],
        cwd=project,
        capture_output=True,
        text=True,
        check=False,
        timeout=600,
        env=os.environ | {"UV_NO_PROGRESS": "1"},
    )
    if proc.returncode == 0:
        report.dependencies_installed = True
    else:
        tail = (proc.stderr or proc.stdout).strip().splitlines()[-6:]
        report.warnings.append("uv sync failed:\n  " + "\n  ".join(tail))


def format_code(project: Path, report: PostGenReport) -> None:
    """Normalise the generated Python with ruff.

    Runs `ruff format` and then `ruff check --fix --select I` (import sorting).

    This is not cosmetic. Jinja's whitespace handling interacts with every
    conditional block, so the exact number of blank lines a template emits
    depends on which features are switched on. No hand-tuned template is
    correct for all of them — verified the hard way — so the output is
    normalised mechanically instead. Without this, a project generated with
    certain feature combinations fails its own CI lint on the first run.

    Uses the project's own venv when dependencies were installed, otherwise
    falls back to `uvx ruff`, so `--no-install` still produces clean output.
    """
    uv = shutil.which("uv")
    if uv is None:
        report.warnings.append("uv not found; run `ruff format . && ruff check --fix .`")
        return

    in_venv = (project / ".venv").is_dir()
    prefix = [uv, "run", "--no-sync", "ruff"] if in_venv else [uv, "tool", "run", "ruff"]

    commands = [
        [*prefix, "format", "."],
        [*prefix, "check", "--fix", "--select", "I", "."],
    ]

    for command in commands:
        proc = subprocess.run(
            command,
            cwd=project,
            capture_output=True,
            text=True,
            check=False,
            timeout=180,
            env=os.environ | {"UV_NO_PROGRESS": "1"},
        )
        if proc.returncode not in (0, 1):  # 1 == ruff found issues it fixed
            report.warnings.append(
                "`ruff` did not run; format manually with `ruff format . && ruff check --fix .`"
            )
            return

    report.formatted = True


def format_terraform(project: Path, report: PostGenReport) -> None:
    """Run `terraform fmt` over the generated infrastructure.

    Same reasoning as `ruff format`: HCL alignment depends on which conditional
    lines a given feature set renders, so no template can be correct for every
    combination. Formatting once here means `terraform fmt -check` passes in CI
    on a project nobody has touched yet.

    Best effort — Terraform is not a requirement for generating a project.
    """
    terraform_dir = project / "terraform"
    if not terraform_dir.is_dir():
        return

    binary = shutil.which("terraform") or shutil.which("tofu")
    if binary is None:
        report.warnings.append(
            "terraform not found; run `terraform fmt -recursive terraform/` "
            "to normalise the generated HCL."
        )
        return

    subprocess.run(
        [binary, "fmt", "-recursive", "terraform"],
        cwd=project,
        capture_output=True,
        text=True,
        check=False,
        timeout=120,
    )


def rotate_secrets(project: Path) -> list[str]:
    """Regenerate every secret in an existing .env. Returns the rotated keys."""
    env_path = project / ENV_FILE
    if not env_path.is_file():
        raise FileNotFoundError(f"No {ENV_FILE} in {project}")

    rotated: list[str] = []
    output: list[str] = []
    for line in env_path.read_text(encoding="utf-8").splitlines():
        if "=" not in line or line.lstrip().startswith("#"):
            output.append(line)
            continue
        key, _, _ = line.partition("=")
        key = key.strip()
        if key in {"SECRET_KEY", "JWT_SECRET", "REFRESH_TOKEN_SECRET", "CSRF_SECRET"}:
            output.append(f"{key}={_new_secret()}")
            rotated.append(key)
        else:
            output.append(line)

    env_path.write_text("\n".join(output) + "\n", encoding="utf-8")
    env_path.chmod(stat.S_IRUSR | stat.S_IWUSR)
    return rotated


def run_all(
    project: Path,
    answers: ProjectAnswers,
    *,
    do_git: bool = True,
    do_install: bool = True,
) -> PostGenReport:
    report = PostGenReport()
    ensure_gitignored(project, report)
    write_env_files(project, answers, report)
    if do_install:
        install_dependencies(project, answers, report)
    # Always: the generated output must lint clean even with --no-install.
    format_code(project, report)
    format_terraform(project, report)
    # Git last: the tree must be final before the initial commit is taken.
    if do_git:
        init_git(project, report)
    return report
