"""Thin wrapper over Copier's Python API.

Design note: this project deliberately does **not** use Copier's ``_tasks``
hook. Post-generation work (git init, secret generation, dependency install)
runs in :mod:`basivo_auth.postgen` instead. That keeps the template free of
executable hooks, so it never needs Copier's ``unsafe=True``, and makes the
post-generation steps unit-testable in isolation.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import copier

from basivo_auth.config import ProjectAnswers

ANSWERS_FILE = ".copier-answers.yml"

#: Where generated projects pull their template from by default.
#:
#: This must be a **git URL**, not the copy bundled in the wheel: ``copier update``
#: compares git tags to compute the diff between template versions, and a
#: directory extracted from a wheel has no git history. The URL is what gets
#: recorded as ``_src_path`` in each project's ``.copier-answers.yml``, so it is
#: also what every future ``basivo-auth update`` will resolve against.
#:
#: Override for a fork or a private mirror with the ``BASIVO_AUTH_TEMPLATE``
#: environment variable, or per-invocation with ``--template``.
DEFAULT_TEMPLATE_URL = "https://github.com/mohamedabubasith/basivo-auth.git"

TEMPLATE_ENV_VAR = "BASIVO_AUTH_TEMPLATE"


class TemplateNotFoundError(RuntimeError):
    pass


class GenerationError(RuntimeError):
    pass


@dataclass(frozen=True, slots=True)
class UpdateTarget:
    path: Path
    answers_file: Path


def bundled_template_path() -> Path:
    """Locate the offline copy of the Copier template.

    Two layouts must both work:

    * installed wheel — force-included at ``basivo_auth/_bundled``
    * editable / raw checkout — the repo root itself holds ``copier.yml``
    """
    here = Path(__file__).resolve().parent

    packaged = here / "_bundled"
    if (packaged / "copier.yml").is_file():
        return packaged

    # src/basivo_auth/runner.py -> src/basivo_auth -> src -> repo root
    checkout = here.parent.parent
    if (checkout / "copier.yml").is_file():
        return checkout

    raise TemplateNotFoundError(
        "Could not locate the bundled Copier template. Looked in "
        f"{packaged} and {checkout}. Reinstall basivo-auth."
    )


def default_template_url() -> str:
    return os.environ.get(TEMPLATE_ENV_VAR, "").strip() or DEFAULT_TEMPLATE_URL


def resolve_template(source: str | None, *, local: bool = False) -> str:
    """Pick the Copier source.

    Precedence: explicit ``--template`` > ``--local`` bundle > ``$BASIVO_AUTH_TEMPLATE``
    > the compiled-in default URL.
    """
    if source:
        return source
    if local:
        return str(bundled_template_path())
    return default_template_url()


def generate(
    answers: ProjectAnswers,
    destination: Path,
    *,
    template: str | None = None,
    local: bool = False,
    vcs_ref: str | None = None,
    overwrite: bool = False,
    pretend: bool = False,
    quiet: bool = True,
) -> Path:
    """Render a new project. Returns the destination path."""
    src = resolve_template(template, local=local)

    if destination.exists() and any(destination.iterdir()) and not overwrite:
        raise GenerationError(
            f"{destination} already exists and is not empty. "
            "Use --overwrite to render into it anyway."
        )

    try:
        copier.run_copy(
            src_path=src,
            dst_path=str(destination),
            data=answers.to_copier(),
            vcs_ref=vcs_ref,
            defaults=True,
            overwrite=overwrite,
            pretend=pretend,
            quiet=quiet,
            unsafe=False,
        )
    except Exception as exc:  # copier raises a wide variety of exception types
        raise GenerationError(f"Copier failed to render the project: {exc}") from exc

    return destination


def find_update_target(start: Path) -> UpdateTarget:
    """Walk upward looking for a Copier-generated project."""
    current = start.resolve()
    for candidate in (current, *current.parents):
        answers_file = candidate / ANSWERS_FILE
        if answers_file.is_file():
            return UpdateTarget(path=candidate, answers_file=answers_file)
    raise GenerationError(
        f"No {ANSWERS_FILE} found in {current} or any parent directory. "
        "Run this from inside a project generated by `basivo-auth new`."
    )


def update(
    target: Path,
    *,
    vcs_ref: str | None = None,
    conflict: Literal["inline", "rej"] = "inline",
    pretend: bool = False,
    quiet: bool = True,
    overrides: dict[str, Any] | None = None,
) -> None:
    """Pull template changes into an existing project via ``copier update``."""
    try:
        copier.run_update(
            dst_path=str(target),
            data=overrides or {},
            vcs_ref=vcs_ref,
            defaults=True,
            overwrite=True,
            conflict=conflict,
            pretend=pretend,
            quiet=quiet,
            unsafe=False,
        )
    except Exception as exc:
        raise GenerationError(
            f"copier update failed: {exc}\n"
            "If the template has drifted too far, `copier recopy` regenerates "
            "from scratch while keeping your answers."
        ) from exc


def recopy(target: Path, *, quiet: bool = True) -> None:
    """Regenerate from scratch, keeping stored answers. The escape hatch."""
    try:
        copier.run_recopy(
            dst_path=str(target),
            defaults=True,
            overwrite=True,
            quiet=quiet,
            unsafe=False,
        )
    except Exception as exc:
        raise GenerationError(f"copier recopy failed: {exc}") from exc
